### ISSUE TITLE
[FEAT] 멋사 4차 과제🦁

### ISSUE THREAD

**Issue by Jiyoongrace** [Likelion-at-SMWU-10th/BaeJiYoon#10]
## 📌  Feature Issue

구현해보고 싶은 웹서비스 아이디어를 설명하는 페이지를 장고 프로젝트로 만들고, 깃헙에 업로드!

## 📝  To-do

- [ ] 웹서비스 아이디어 정리
- [ ] html 파일로 제작 + css 활용
- [ ] 장고 프로젝트로 만들기
- [ ] 깃헙에 업로드

**Comment by biiit4894** [comment]
과제 고생하셨읍니다. 세션날 슬쩍 훔쳐본 당신의 피그마.. 나 두근거리고 있어요.
