### ISSUE TITLE
[FEAT] 멋사 6차 과제🦁

### ISSUE THREAD

**Issue by Jiyoongrace** [Likelion-at-SMWU-10th/BaeJiYoon#12]
## 📌  Feature Issue

자바스크립트 실습하기

## 📝  To-do

- [ ] 일단 만드는 자바스크립트 강의 듣기
- [ ] 6주차 세미나 실습 다시 반복하기
- [ ] 라이브 서버 화면 캡쳐하기
