### ISSUE TITLE
[FEAT] 멋사 프론트 6차 필수 과제🦁

### ISSUE THREAD

**Issue by Jiyoongrace** [Likelion-at-SMWU-10th/BaeJiYoon#14]
## 📌  Feature Issue

리액트 라우터 페이지를 연결하여,
상위 라우터 element와 하위 라우터 element가
동시에 보일 수 있는 앱 만들기

## 📝  To-do

- [ ] 프로젝트 생성 및 라이브러리 설치
- [ ] 프로젝트에 라우터 적용, 컴포넌트 페이지 만들기
- [ ] Route 컴포넌트로 특정 주소에 컴포넌트 연결하기
- [ ] Navbar를 페이지들의 공통 레이아웃 컴포넌트로 만들기
